import { describe, it, expect, vi, beforeEach } from "vitest";
import { buildPlatformMetadataJson } from "@/lib/export/metadata-json-builder";
import type { BookMetadata } from "@/server/db/schema/book-metadata";

describe("buildPlatformMetadataJson", () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-01-15T10:00:00.000Z"));
  });

  const mockMetadata: BookMetadata = {
    id: "meta-1",
    bookId: "book-1",
    description: "A great book about testing",
    keywords: ["testing", "software", "quality"],
    category: "Technology",
    price: "14.99",
    descriptionAutoGenerated: false,
    keywordsAutoGenerated: false,
    categoryAutoGenerated: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  it("builds correct metadata JSON for KDP", () => {
    const result = buildPlatformMetadataJson(
      { title: "Test Book" },
      mockMetadata,
      "KDP"
    );

    expect(result.platform).toBe("KDP");
    expect(result.title).toBe("Test Book");
    expect(result.description).toBe("A great book about testing");
    expect(result.keywords).toEqual(["testing", "software", "quality"]);
    expect(result.category).toBe("Technology");
    expect(result.price).toBe("14.99");
    expect(result.language).toBe("en");
    expect(result.publisher).toBe("Inkfluence AI");
  });

  it("includes generatedAt timestamp", () => {
    const result = buildPlatformMetadataJson(
      { title: "Test" },
      mockMetadata,
      "AB"
    );
    expect(result.generatedAt).toBe("2026-01-15T10:00:00.000Z");
  });

  it("uses authorName when provided", () => {
    const result = buildPlatformMetadataJson(
      { title: "Test", authorName: "Jane Doe" },
      mockMetadata,
      "KDP"
    );
    expect(result.author).toBe("Jane Doe");
  });

  it("defaults to Unknown Author when authorName is null", () => {
    const result = buildPlatformMetadataJson(
      { title: "Test", authorName: null },
      mockMetadata,
      "GP"
    );
    expect(result.author).toBe("Unknown Author");
  });

  it("defaults to Unknown Author when authorName is omitted", () => {
    const result = buildPlatformMetadataJson(
      { title: "Test" },
      mockMetadata,
      "KO"
    );
    expect(result.author).toBe("Unknown Author");
  });

  it("handles null metadata gracefully", () => {
    const result = buildPlatformMetadataJson(
      { title: "No Metadata Book" },
      null,
      "KDP"
    );

    expect(result.title).toBe("No Metadata Book");
    expect(result.description).toBeNull();
    expect(result.keywords).toEqual([]);
    expect(result.category).toBeNull();
    expect(result.price).toBe("9.99");
  });

  it("sets correct platform code for each platform", () => {
    const platforms = ["KDP", "AB", "GP", "KO"] as const;
    for (const code of platforms) {
      const result = buildPlatformMetadataJson(
        { title: "Test" },
        mockMetadata,
        code
      );
      expect(result.platform).toBe(code);
    }
  });

  it("uses default price 9.99 when metadata has no price", () => {
    const metaNoPrice = { ...mockMetadata, price: undefined } as unknown as BookMetadata;
    const result = buildPlatformMetadataJson(
      { title: "Test" },
      metaNoPrice,
      "KDP"
    );
    expect(result.price).toBe("9.99");
  });
});
