import { z } from "zod";

/** Validates POST /api/metadata/generate request body */
export const metadataGenerateRequestSchema = z.object({
  bookId: z.string().uuid("Invalid book ID"),
});

/** Validates Claude tool_use response for metadata generation */
export const metadataGenerationResponseSchema = z.object({
  description: z.string().min(1),
  keywords: z.array(z.string().min(1)).max(7),
  category: z.string().min(1),
});

export type ValidatedMetadataResponse = z.infer<
  typeof metadataGenerationResponseSchema
>;

/** Validates metadata update from user edits */
export const updateBookMetadataSchema = z.object({
  description: z.string().max(2000).nullable().optional(),
  keywords: z.array(z.string().max(50)).max(7).optional(),
  category: z.string().max(100).nullable().optional(),
  price: z
    .string()
    .regex(/^\d+(\.\d{1,2})?$/, "Invalid price format")
    .optional(),
  descriptionAutoGenerated: z.boolean().optional(),
  keywordsAutoGenerated: z.boolean().optional(),
  categoryAutoGenerated: z.boolean().optional(),
});

export type UpdateBookMetadataInput = z.infer<typeof updateBookMetadataSchema>;
