import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, it, expect, vi } from "vitest";
import { MetadataCard } from "../metadata-card";
import type { MetadataCardProps } from "../metadata-card";
import type { BookMetadata } from "@/server/db/schema/book-metadata";

const mockMetadata: BookMetadata = {
  id: "meta-uuid-123",
  bookId: "book-uuid-123",
  description: "A great book about growth.",
  keywords: ["SaaS", "growth"],
  category: "Business & Money",
  price: "9.99",
  descriptionAutoGenerated: true,
  keywordsAutoGenerated: true,
  categoryAutoGenerated: true,
  createdAt: new Date(),
  updatedAt: new Date(),
};

function renderCard(overrides: Partial<MetadataCardProps> = {}) {
  const defaultProps: MetadataCardProps = {
    metadata: mockMetadata,
    onGenerate: vi.fn(),
    onSave: vi.fn(),
    isGenerating: false,
    isSaving: false,
    ...overrides,
  };
  return {
    ...render(<MetadataCard {...defaultProps} />),
    props: defaultProps,
  };
}

describe("MetadataCard", () => {
  it("renders metadata title", () => {
    renderCard();
    expect(screen.getByText("Metadata")).toBeInTheDocument();
  });

  it("renders Generate with AI button", () => {
    renderCard();
    expect(screen.getByText("Generate with AI")).toBeInTheDocument();
  });

  it("shows Auto-generated badge when flags are true", () => {
    renderCard();
    expect(screen.getByText("Auto-generated")).toBeInTheDocument();
  });

  it("hides Auto-generated badge when no flags are true", () => {
    renderCard({
      metadata: {
        ...mockMetadata,
        descriptionAutoGenerated: false,
        keywordsAutoGenerated: false,
        categoryAutoGenerated: false,
      },
    });
    expect(screen.queryByText("Auto-generated")).not.toBeInTheDocument();
  });

  it("renders description textarea with current value", () => {
    renderCard();
    const textarea = screen.getByPlaceholderText(
      "A compelling description of your book..."
    );
    expect(textarea).toHaveValue("A great book about growth.");
  });

  it("renders keyword badges", () => {
    renderCard();
    expect(screen.getByText("SaaS")).toBeInTheDocument();
    expect(screen.getByText("growth")).toBeInTheDocument();
  });

  it("renders Add keyword button", () => {
    renderCard();
    expect(screen.getByText("+ Add")).toBeInTheDocument();
  });

  it("renders price input with default value", () => {
    renderCard();
    const priceInput = screen.getByDisplayValue("9.99");
    expect(priceInput).toBeInTheDocument();
  });

  it("calls onGenerate when generate button clicked", async () => {
    const user = userEvent.setup();
    const onGenerate = vi.fn();
    renderCard({ onGenerate });

    await user.click(screen.getByText("Generate with AI"));
    expect(onGenerate).toHaveBeenCalledTimes(1);
  });

  it("shows Generating... text when isGenerating is true", () => {
    renderCard({ isGenerating: true });
    expect(screen.getByText("Generating...")).toBeInTheDocument();
  });

  it("disables generate button when isGenerating", () => {
    renderCard({ isGenerating: true });
    const button = screen.getByText("Generating...").closest("button");
    expect(button).toBeDisabled();
  });

  it("calls onSave when save button clicked", async () => {
    const user = userEvent.setup();
    const onSave = vi.fn();
    renderCard({ onSave });

    await user.click(screen.getByText("Save Metadata"));
    expect(onSave).toHaveBeenCalledTimes(1);
  });

  it("shows Saving... when isSaving is true", () => {
    renderCard({ isSaving: true });
    expect(screen.getByText("Saving...")).toBeInTheDocument();
  });

  it("renders with null metadata", () => {
    renderCard({ metadata: null });
    const textarea = screen.getByPlaceholderText(
      "A compelling description of your book..."
    );
    expect(textarea).toHaveValue("");
  });

  it("renders Save Metadata button", () => {
    renderCard();
    expect(screen.getByText("Save Metadata")).toBeInTheDocument();
  });
});
