import {
  pgTable,
  text,
  timestamp,
  uuid,
  jsonb,
  boolean,
} from "drizzle-orm/pg-core";
import { books } from "./books";

export const bookMetadata = pgTable("book_metadata", {
  id: uuid("id").primaryKey().defaultRandom(),
  bookId: uuid("book_id")
    .notNull()
    .references(() => books.id, { onDelete: "cascade" })
    .unique(),
  description: text("description"),
  keywords: jsonb("keywords").$type<string[]>().notNull().default([]),
  category: text("category"),
  price: text("price").notNull().default("9.99"),
  descriptionAutoGenerated: boolean("description_auto_generated")
    .notNull()
    .default(false),
  keywordsAutoGenerated: boolean("keywords_auto_generated")
    .notNull()
    .default(false),
  categoryAutoGenerated: boolean("category_auto_generated")
    .notNull()
    .default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export type BookMetadata = typeof bookMetadata.$inferSelect;
export type NewBookMetadata = typeof bookMetadata.$inferInsert;
