import { describe, it, expect } from "vitest";
import {
  metadataGenerateRequestSchema,
  metadataGenerationResponseSchema,
  updateBookMetadataSchema,
} from "../book-metadata";

describe("metadataGenerateRequestSchema", () => {
  it("accepts valid UUID bookId", () => {
    const result = metadataGenerateRequestSchema.safeParse({
      bookId: "550e8400-e29b-41d4-a716-446655440000",
    });
    expect(result.success).toBe(true);
  });

  it("rejects non-UUID bookId", () => {
    const result = metadataGenerateRequestSchema.safeParse({
      bookId: "not-a-uuid",
    });
    expect(result.success).toBe(false);
  });

  it("rejects missing bookId", () => {
    const result = metadataGenerateRequestSchema.safeParse({});
    expect(result.success).toBe(false);
  });
});

describe("metadataGenerationResponseSchema", () => {
  const validResponse = {
    description: "A compelling book about SaaS growth strategies.",
    keywords: ["SaaS", "growth", "startup"],
    category: "Business & Money",
  };

  it("accepts valid response", () => {
    const result = metadataGenerationResponseSchema.safeParse(validResponse);
    expect(result.success).toBe(true);
  });

  it("accepts response with 7 keywords", () => {
    const result = metadataGenerationResponseSchema.safeParse({
      ...validResponse,
      keywords: ["a", "b", "c", "d", "e", "f", "g"],
    });
    expect(result.success).toBe(true);
  });

  it("rejects response with more than 7 keywords", () => {
    const result = metadataGenerationResponseSchema.safeParse({
      ...validResponse,
      keywords: ["a", "b", "c", "d", "e", "f", "g", "h"],
    });
    expect(result.success).toBe(false);
  });

  it("rejects empty description", () => {
    const result = metadataGenerationResponseSchema.safeParse({
      ...validResponse,
      description: "",
    });
    expect(result.success).toBe(false);
  });

  it("rejects missing category", () => {
    const { category: _, ...noCategory } = validResponse;
    const result = metadataGenerationResponseSchema.safeParse(noCategory);
    expect(result.success).toBe(false);
  });

  it("rejects empty keywords in array", () => {
    const result = metadataGenerationResponseSchema.safeParse({
      ...validResponse,
      keywords: ["valid", ""],
    });
    expect(result.success).toBe(false);
  });
});

describe("updateBookMetadataSchema", () => {
  it("accepts valid partial update", () => {
    const result = updateBookMetadataSchema.safeParse({
      description: "Updated description",
    });
    expect(result.success).toBe(true);
  });

  it("accepts full update", () => {
    const result = updateBookMetadataSchema.safeParse({
      description: "Updated description",
      keywords: ["keyword1", "keyword2"],
      category: "Technology",
      price: "12.99",
      descriptionAutoGenerated: false,
      keywordsAutoGenerated: false,
      categoryAutoGenerated: false,
    });
    expect(result.success).toBe(true);
  });

  it("accepts null description", () => {
    const result = updateBookMetadataSchema.safeParse({
      description: null,
    });
    expect(result.success).toBe(true);
  });

  it("rejects invalid price format", () => {
    const result = updateBookMetadataSchema.safeParse({
      price: "abc",
    });
    expect(result.success).toBe(false);
  });

  it("accepts valid price formats", () => {
    expect(
      updateBookMetadataSchema.safeParse({ price: "9.99" }).success
    ).toBe(true);
    expect(
      updateBookMetadataSchema.safeParse({ price: "0" }).success
    ).toBe(true);
    expect(
      updateBookMetadataSchema.safeParse({ price: "19" }).success
    ).toBe(true);
    expect(
      updateBookMetadataSchema.safeParse({ price: "9.9" }).success
    ).toBe(true);
  });

  it("rejects price with three decimal places", () => {
    const result = updateBookMetadataSchema.safeParse({
      price: "9.999",
    });
    expect(result.success).toBe(false);
  });

  it("rejects more than 7 keywords", () => {
    const result = updateBookMetadataSchema.safeParse({
      keywords: ["a", "b", "c", "d", "e", "f", "g", "h"],
    });
    expect(result.success).toBe(false);
  });

  it("rejects description over 2000 chars", () => {
    const result = updateBookMetadataSchema.safeParse({
      description: "x".repeat(2001),
    });
    expect(result.success).toBe(false);
  });

  it("accepts empty object", () => {
    const result = updateBookMetadataSchema.safeParse({});
    expect(result.success).toBe(true);
  });
});
