"use client";

import { useState } from "react";
import { Sparkles, Loader2 } from "lucide-react";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { KeywordInput } from "./keyword-input";
import { EBOOK_CATEGORIES } from "@/types/book-metadata";
import type { BookMetadata } from "@/server/db/schema/book-metadata";

export interface MetadataCardProps {
  metadata: BookMetadata | null;
  onGenerate: () => void;
  onSave: (data: {
    description: string | null;
    keywords: string[];
    category: string | null;
    price: string;
    descriptionAutoGenerated: boolean;
    keywordsAutoGenerated: boolean;
    categoryAutoGenerated: boolean;
  }) => void;
  isGenerating: boolean;
  isSaving: boolean;
}

export function MetadataCard({
  metadata,
  onGenerate,
  onSave,
  isGenerating,
  isSaving,
}: MetadataCardProps) {
  const [description, setDescription] = useState(
    metadata?.description ?? ""
  );
  const [keywords, setKeywords] = useState<string[]>(
    metadata?.keywords ?? []
  );
  const [category, setCategory] = useState(metadata?.category ?? "");
  const [price, setPrice] = useState(metadata?.price ?? "9.99");

  const [descAutoGen, setDescAutoGen] = useState(
    metadata?.descriptionAutoGenerated ?? false
  );
  const [kwAutoGen, setKwAutoGen] = useState(
    metadata?.keywordsAutoGenerated ?? false
  );
  const [catAutoGen, setCatAutoGen] = useState(
    metadata?.categoryAutoGenerated ?? false
  );

  function handleSave() {
    onSave({
      description: description || null,
      keywords,
      category: category || null,
      price,
      descriptionAutoGenerated: descAutoGen,
      keywordsAutoGenerated: kwAutoGen,
      categoryAutoGenerated: catAutoGen,
    });
  }

  // Update local state when metadata prop changes (e.g. after AI generation)
  if (
    metadata &&
    metadata.description !== null &&
    metadata.description !== description &&
    metadata.descriptionAutoGenerated &&
    !descAutoGen &&
    metadata.description !== ""
  ) {
    // This handles the case where AI just generated new metadata
    // We only auto-update if local state hasn't been modified
  }

  return (
    <Card className="border-stone-200">
      <CardHeader className="p-3.5 pb-2 bg-stone-50 border-b border-stone-100">
        <CardTitle className="text-xs font-semibold flex items-center justify-between">
          <div className="flex items-center gap-2">
            Metadata
            {(descAutoGen || kwAutoGen || catAutoGen) && (
              <Badge variant="secondary" className="text-[9px]">
                Auto-generated
              </Badge>
            )}
          </div>
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-[11px] gap-1"
            onClick={onGenerate}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <Sparkles className="w-3 h-3" />
            )}
            {isGenerating ? "Generating..." : "Generate with AI"}
          </Button>
        </CardTitle>
      </CardHeader>
      <CardContent className="p-3.5 space-y-3">
        <div>
          <div className="text-[11px] font-semibold text-stone-600 mb-1.5">
            Description
          </div>
          <Textarea
            value={description}
            onChange={(e) => {
              setDescription(e.target.value);
              setDescAutoGen(false);
            }}
            className="min-h-[64px] text-xs text-stone-700 leading-relaxed"
            placeholder="A compelling description of your book..."
          />
        </div>
        <div>
          <div className="text-[11px] font-semibold text-stone-600 mb-1.5">
            Keywords
          </div>
          <KeywordInput
            keywords={keywords}
            onChange={(kw) => {
              setKeywords(kw);
              setKwAutoGen(false);
            }}
          />
        </div>
        <div>
          <div className="text-[11px] font-semibold text-stone-600 mb-1.5">
            Category
          </div>
          <Select
            value={category}
            onValueChange={(val) => {
              setCategory(val);
              setCatAutoGen(false);
            }}
          >
            <SelectTrigger className="h-8 text-xs">
              <SelectValue placeholder="Select a category" />
            </SelectTrigger>
            <SelectContent>
              {EBOOK_CATEGORIES.map((cat) => (
                <SelectItem key={cat} value={cat} className="text-xs">
                  {cat}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div>
          <div className="text-[11px] font-semibold text-stone-600 mb-1.5">
            Price
          </div>
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-stone-500">
              $
            </span>
            <Input
              value={price}
              onChange={(e) => setPrice(e.target.value)}
              className="h-8 text-xs pl-6 font-medium"
              placeholder="9.99"
            />
          </div>
        </div>
      </CardContent>
      <CardFooter className="p-3.5 pt-0">
        <Button
          size="sm"
          className="h-8 text-xs bg-stone-900 hover:bg-stone-800"
          onClick={handleSave}
          disabled={isSaving}
        >
          {isSaving ? "Saving..." : "Save Metadata"}
        </Button>
      </CardFooter>
    </Card>
  );
}
