"use client";

import { useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PrePublishChecklist } from "./pre-publish-checklist";
import { MetadataCard } from "./metadata-card";
import { saveBookMetadataAction } from "@/server/actions/book-metadata";
import type { PrePublishChecklistItem } from "@/types/book-metadata";
import type { BookMetadata } from "@/server/db/schema/book-metadata";

export interface PublishPageClientProps {
  bookId: string;
  checklistItems: PrePublishChecklistItem[];
  metadata: BookMetadata | null;
}

export function PublishPageClient({
  bookId,
  checklistItems,
  metadata: initialMetadata,
}: PublishPageClientProps) {
  const router = useRouter();
  const [metadata, setMetadata] = useState(initialMetadata);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const handleGenerate = useCallback(async () => {
    setIsGenerating(true);
    try {
      const res = await fetch("/api/metadata/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bookId }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to generate metadata");
      }

      router.refresh();
      const data = await res.json();
      setMetadata((prev) => ({
        ...(prev ?? {
          id: data.metadataId,
          bookId,
          price: "9.99",
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
        id: data.metadataId ?? prev?.id ?? "",
        bookId,
        description: data.description,
        keywords: data.keywords,
        category: data.category,
        descriptionAutoGenerated: true,
        keywordsAutoGenerated: true,
        categoryAutoGenerated: true,
        price: prev?.price ?? "9.99",
        createdAt: prev?.createdAt ?? new Date(),
        updatedAt: new Date(),
      }));
    } catch (err) {
      console.error("Metadata generation failed:", err);
    } finally {
      setIsGenerating(false);
    }
  }, [bookId, router]);

  const handleSave = useCallback(
    async (data: {
      description: string | null;
      keywords: string[];
      category: string | null;
      price: string;
      descriptionAutoGenerated: boolean;
      keywordsAutoGenerated: boolean;
      categoryAutoGenerated: boolean;
    }) => {
      setIsSaving(true);
      try {
        const result = await saveBookMetadataAction(bookId, data);
        if (!result.success) {
          console.error("Save failed:", result.error);
          return;
        }
        setMetadata((prev) => ({
          ...(prev ?? {
            id: result.data.id,
            bookId,
            createdAt: new Date(),
          }),
          id: result.data.id ?? prev?.id ?? "",
          bookId,
          description: data.description,
          keywords: data.keywords,
          category: data.category,
          price: data.price,
          descriptionAutoGenerated: data.descriptionAutoGenerated,
          keywordsAutoGenerated: data.keywordsAutoGenerated,
          categoryAutoGenerated: data.categoryAutoGenerated,
          updatedAt: new Date(),
          createdAt: prev?.createdAt ?? new Date(),
        }));
        router.refresh();
      } catch (err) {
        console.error("Save failed:", err);
      } finally {
        setIsSaving(false);
      }
    },
    [bookId, router]
  );

  return (
    <div className="flex-1 bg-stone-50/50 p-5 overflow-y-auto">
      <PrePublishChecklist bookId={bookId} items={checklistItems} />
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-5">
        <MetadataCard
          metadata={metadata}
          onGenerate={handleGenerate}
          onSave={handleSave}
          isGenerating={isGenerating}
          isSaving={isSaving}
        />
        <Card className="border-stone-200">
          <CardHeader className="p-3.5 pb-2 bg-stone-50 border-b border-stone-100">
            <CardTitle className="text-xs font-semibold">
              Publishing Platforms
            </CardTitle>
          </CardHeader>
          <CardContent className="p-3.5">
            <p className="text-xs text-stone-400">
              Platform connections coming soon.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
